apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: nacho270/docker-fibonacci-calculator-client #image: stephengrider/multi-client
      ports:
        - containerPort: 3000
