apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
    - port: 3050 # accessed by another pod or container
      targetPort: 3000 # same as in pod definition
      nodePort: 31515 # the most important. Access through the browser.
  selector:
    component: web
